server {
    listen 80;
    server_name localhost;

    # Set the absolute root path for the server
    root /usr/share/nginx/html;

    # Catch everything under /dashboard
    location /dashboard {
        index index.html;
        # If the file isn't found, redirect the request to React's index.html
        try_files $uri $uri/ /dashboard/index.html;
    }
}